data:
  gpu: 0
  num_workers: 1
  train_dataset: ../right-for-the-wrong-reason/contaminated_data/chexpert/Cardiomegaly/hyperintensities/degree3/train_df.csv
  dataset_name: chexpert
  num_classes: 2
training:
  arch: resnet50
  batch_size: 8
  epochs: 20
  lr: 1e-4
  optimizer: Adam
  weight_decay: 1.0
  lr_tta: false
  num_workers: 6
  save_dir: outputs/chexpert/
  eval_freq: -1
  exp_name: chexpert-Cardiomegaly-hyperintensities-degree3
  pretrained: True
  n_trials: 1
  seed: 0